version: '3'

services:
  php74:
    container_name: php7.4
#    build: ./php
    image: php:7.4-fpm-redis-xdebug
    tty: true
    restart: always
    expose:
      - "9000"
    volumes:
      - /Users/lijiageng/work/duomei:/data01
      - ./php/conf:/usr/local/etc
      - ./php/log:/usr/local/var/log:rw
    depends_on:
      - mysql
      - redis
    links:
      - mysql:mysql
      - redis:redis
  nginx:
    container_name: nginx
    image: nginx:stable
    tty: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "9998:9998"
    volumes:
      - /Users/lijiageng/work/duomei:/data01
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    depends_on:
      - php74
    links:
      - php74
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    container_name: redis
    image: redis:5.0-buster
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/config/redis.conf:/redis.conf
      - ./redis/log:/var/log/redis
    command: redis-server /redis.conf --appendonly yes